### ISSUE TITLE
Insert multiple rows

### ISSUE THREAD

**Issue by ik9999** [ulule/loukoum#71]
Is it possible to build an Insert query for inserting multiple rows i.e.
```
INSERT INTO MyTable ( Column1, Column2, Column3 )
VALUES ('John', 123, 'Lloyds Office'), 
('Jane', 124, 'Lloyds Office'), 
('Billy', 125, 'London Office'),
('Miranda', 126, 'Bristol Office');
```
?
Thanks.

**Comment by novln** [comment]
Hello,

At the moment it's not possible :confused: 
However, you can create a common builder for the insert statement with `INSERT INTO MyTable ( Column1, Column2, Column3 )` clause and reuse that instance multiple times with the number of rows you have to insert to create new builders from that common instance.

I'm not sure we'll support this feature since it will drastically complexify the codebase.
However, we'll gladly review pull request, if many developers require that feature.

Cheers,
